[package]
name = "editorsrv"
version = "0.0.1"
authors = [ "smallt@gmail.com" ]
edition = "2018"


[dependencies]
notify = "4.0.12"
tungstenite = "0.10.1"
serde_json = "1.0"
fancy-regex = "0.3.3"
base64 = "0.12.0"